// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Building.proto

public final class BuildingOuterClass {
  private BuildingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 building_code = 1;</code>
     * @return Whether the buildingCode field is set.
     */
    boolean hasBuildingCode();
    /**
     * <code>required int64 building_code = 1;</code>
     * @return The buildingCode.
     */
    long getBuildingCode();

    /**
     * <code>required int32 total_floors = 2;</code>
     * @return Whether the totalFloors field is set.
     */
    boolean hasTotalFloors();
    /**
     * <code>required int32 total_floors = 2;</code>
     * @return The totalFloors.
     */
    int getTotalFloors();

    /**
     * <code>required int32 companies_in_the_building = 3;</code>
     * @return Whether the companiesInTheBuilding field is set.
     */
    boolean hasCompaniesInTheBuilding();
    /**
     * <code>required int32 companies_in_the_building = 3;</code>
     * @return The companiesInTheBuilding.
     */
    int getCompaniesInTheBuilding();

    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return Whether the cafeteriaCode field is set.
     */
    boolean hasCafeteriaCode();
    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return The cafeteriaCode.
     */
    java.lang.String getCafeteriaCode();
    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return The bytes for cafeteriaCode.
     */
    com.google.protobuf.ByteString
        getCafeteriaCodeBytes();
  }
  /**
   * Protobuf type {@code Building}
   */
  public static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      cafeteriaCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              buildingCode_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalFloors_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              companiesInTheBuilding_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cafeteriaCode_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BuildingOuterClass.internal_static_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BuildingOuterClass.internal_static_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BuildingOuterClass.Building.class, BuildingOuterClass.Building.Builder.class);
    }

    private int bitField0_;
    public static final int BUILDING_CODE_FIELD_NUMBER = 1;
    private long buildingCode_;
    /**
     * <code>required int64 building_code = 1;</code>
     * @return Whether the buildingCode field is set.
     */
    @java.lang.Override
    public boolean hasBuildingCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 building_code = 1;</code>
     * @return The buildingCode.
     */
    @java.lang.Override
    public long getBuildingCode() {
      return buildingCode_;
    }

    public static final int TOTAL_FLOORS_FIELD_NUMBER = 2;
    private int totalFloors_;
    /**
     * <code>required int32 total_floors = 2;</code>
     * @return Whether the totalFloors field is set.
     */
    @java.lang.Override
    public boolean hasTotalFloors() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 total_floors = 2;</code>
     * @return The totalFloors.
     */
    @java.lang.Override
    public int getTotalFloors() {
      return totalFloors_;
    }

    public static final int COMPANIES_IN_THE_BUILDING_FIELD_NUMBER = 3;
    private int companiesInTheBuilding_;
    /**
     * <code>required int32 companies_in_the_building = 3;</code>
     * @return Whether the companiesInTheBuilding field is set.
     */
    @java.lang.Override
    public boolean hasCompaniesInTheBuilding() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 companies_in_the_building = 3;</code>
     * @return The companiesInTheBuilding.
     */
    @java.lang.Override
    public int getCompaniesInTheBuilding() {
      return companiesInTheBuilding_;
    }

    public static final int CAFETERIA_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object cafeteriaCode_;
    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return Whether the cafeteriaCode field is set.
     */
    @java.lang.Override
    public boolean hasCafeteriaCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return The cafeteriaCode.
     */
    @java.lang.Override
    public java.lang.String getCafeteriaCode() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cafeteriaCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cafeteria_code = 4;</code>
     * @return The bytes for cafeteriaCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCafeteriaCodeBytes() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cafeteriaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBuildingCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalFloors()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompaniesInTheBuilding()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCafeteriaCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, buildingCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, totalFloors_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, companiesInTheBuilding_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cafeteriaCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, buildingCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalFloors_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, companiesInTheBuilding_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cafeteriaCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BuildingOuterClass.Building)) {
        return super.equals(obj);
      }
      BuildingOuterClass.Building other = (BuildingOuterClass.Building) obj;

      if (hasBuildingCode() != other.hasBuildingCode()) return false;
      if (hasBuildingCode()) {
        if (getBuildingCode()
            != other.getBuildingCode()) return false;
      }
      if (hasTotalFloors() != other.hasTotalFloors()) return false;
      if (hasTotalFloors()) {
        if (getTotalFloors()
            != other.getTotalFloors()) return false;
      }
      if (hasCompaniesInTheBuilding() != other.hasCompaniesInTheBuilding()) return false;
      if (hasCompaniesInTheBuilding()) {
        if (getCompaniesInTheBuilding()
            != other.getCompaniesInTheBuilding()) return false;
      }
      if (hasCafeteriaCode() != other.hasCafeteriaCode()) return false;
      if (hasCafeteriaCode()) {
        if (!getCafeteriaCode()
            .equals(other.getCafeteriaCode())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuildingCode()) {
        hash = (37 * hash) + BUILDING_CODE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBuildingCode());
      }
      if (hasTotalFloors()) {
        hash = (37 * hash) + TOTAL_FLOORS_FIELD_NUMBER;
        hash = (53 * hash) + getTotalFloors();
      }
      if (hasCompaniesInTheBuilding()) {
        hash = (37 * hash) + COMPANIES_IN_THE_BUILDING_FIELD_NUMBER;
        hash = (53 * hash) + getCompaniesInTheBuilding();
      }
      if (hasCafeteriaCode()) {
        hash = (37 * hash) + CAFETERIA_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCafeteriaCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BuildingOuterClass.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BuildingOuterClass.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BuildingOuterClass.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BuildingOuterClass.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BuildingOuterClass.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BuildingOuterClass.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BuildingOuterClass.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BuildingOuterClass.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BuildingOuterClass.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BuildingOuterClass.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BuildingOuterClass.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BuildingOuterClass.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BuildingOuterClass.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Building)
        BuildingOuterClass.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BuildingOuterClass.internal_static_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BuildingOuterClass.internal_static_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BuildingOuterClass.Building.class, BuildingOuterClass.Building.Builder.class);
      }

      // Construct using BuildingOuterClass.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        totalFloors_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        companiesInTheBuilding_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        cafeteriaCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BuildingOuterClass.internal_static_Building_descriptor;
      }

      @java.lang.Override
      public BuildingOuterClass.Building getDefaultInstanceForType() {
        return BuildingOuterClass.Building.getDefaultInstance();
      }

      @java.lang.Override
      public BuildingOuterClass.Building build() {
        BuildingOuterClass.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BuildingOuterClass.Building buildPartial() {
        BuildingOuterClass.Building result = new BuildingOuterClass.Building(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingCode_ = buildingCode_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.totalFloors_ = totalFloors_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.companiesInTheBuilding_ = companiesInTheBuilding_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cafeteriaCode_ = cafeteriaCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BuildingOuterClass.Building) {
          return mergeFrom((BuildingOuterClass.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BuildingOuterClass.Building other) {
        if (other == BuildingOuterClass.Building.getDefaultInstance()) return this;
        if (other.hasBuildingCode()) {
          setBuildingCode(other.getBuildingCode());
        }
        if (other.hasTotalFloors()) {
          setTotalFloors(other.getTotalFloors());
        }
        if (other.hasCompaniesInTheBuilding()) {
          setCompaniesInTheBuilding(other.getCompaniesInTheBuilding());
        }
        if (other.hasCafeteriaCode()) {
          bitField0_ |= 0x00000008;
          cafeteriaCode_ = other.cafeteriaCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasBuildingCode()) {
          return false;
        }
        if (!hasTotalFloors()) {
          return false;
        }
        if (!hasCompaniesInTheBuilding()) {
          return false;
        }
        if (!hasCafeteriaCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BuildingOuterClass.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BuildingOuterClass.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long buildingCode_ ;
      /**
       * <code>required int64 building_code = 1;</code>
       * @return Whether the buildingCode field is set.
       */
      @java.lang.Override
      public boolean hasBuildingCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 building_code = 1;</code>
       * @return The buildingCode.
       */
      @java.lang.Override
      public long getBuildingCode() {
        return buildingCode_;
      }
      /**
       * <code>required int64 building_code = 1;</code>
       * @param value The buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCode(long value) {
        bitField0_ |= 0x00000001;
        buildingCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 building_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buildingCode_ = 0L;
        onChanged();
        return this;
      }

      private int totalFloors_ ;
      /**
       * <code>required int32 total_floors = 2;</code>
       * @return Whether the totalFloors field is set.
       */
      @java.lang.Override
      public boolean hasTotalFloors() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 total_floors = 2;</code>
       * @return The totalFloors.
       */
      @java.lang.Override
      public int getTotalFloors() {
        return totalFloors_;
      }
      /**
       * <code>required int32 total_floors = 2;</code>
       * @param value The totalFloors to set.
       * @return This builder for chaining.
       */
      public Builder setTotalFloors(int value) {
        bitField0_ |= 0x00000002;
        totalFloors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total_floors = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalFloors() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalFloors_ = 0;
        onChanged();
        return this;
      }

      private int companiesInTheBuilding_ ;
      /**
       * <code>required int32 companies_in_the_building = 3;</code>
       * @return Whether the companiesInTheBuilding field is set.
       */
      @java.lang.Override
      public boolean hasCompaniesInTheBuilding() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 companies_in_the_building = 3;</code>
       * @return The companiesInTheBuilding.
       */
      @java.lang.Override
      public int getCompaniesInTheBuilding() {
        return companiesInTheBuilding_;
      }
      /**
       * <code>required int32 companies_in_the_building = 3;</code>
       * @param value The companiesInTheBuilding to set.
       * @return This builder for chaining.
       */
      public Builder setCompaniesInTheBuilding(int value) {
        bitField0_ |= 0x00000004;
        companiesInTheBuilding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 companies_in_the_building = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompaniesInTheBuilding() {
        bitField0_ = (bitField0_ & ~0x00000004);
        companiesInTheBuilding_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cafeteriaCode_ = "";
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @return Whether the cafeteriaCode field is set.
       */
      public boolean hasCafeteriaCode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @return The cafeteriaCode.
       */
      public java.lang.String getCafeteriaCode() {
        java.lang.Object ref = cafeteriaCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cafeteriaCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @return The bytes for cafeteriaCode.
       */
      public com.google.protobuf.ByteString
          getCafeteriaCodeBytes() {
        java.lang.Object ref = cafeteriaCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cafeteriaCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @param value The cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCafeteriaCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cafeteriaCode_ = getDefaultInstance().getCafeteriaCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string cafeteria_code = 4;</code>
       * @param value The bytes for cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Building)
    }

    // @@protoc_insertion_point(class_scope:Building)
    private static final BuildingOuterClass.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BuildingOuterClass.Building();
    }

    public static BuildingOuterClass.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BuildingOuterClass.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Building_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Building.proto\"r\n\010Building\022\025\n\rbuilding" +
      "_code\030\001 \002(\003\022\024\n\014total_floors\030\002 \002(\005\022!\n\031com" +
      "panies_in_the_building\030\003 \002(\005\022\026\n\016cafeteri" +
      "a_code\030\004 \002(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Building_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Building_descriptor,
        new java.lang.String[] { "BuildingCode", "TotalFloors", "CompaniesInTheBuilding", "CafeteriaCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
