// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *unique numbers that are used for serializing and deserializing data
     * </pre>
     *
     * <code>required int64 employee_id = 1;</code>
     * @return Whether the employeeId field is set.
     */
    boolean hasEmployeeId();
    /**
     * <pre>
     *unique numbers that are used for serializing and deserializing data
     * </pre>
     *
     * <code>required int64 employee_id = 1;</code>
     * @return The employeeId.
     */
    long getEmployeeId();

    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 building_code = 3;</code>
     * @return Whether the buildingCode field is set.
     */
    boolean hasBuildingCode();
    /**
     * <code>required int32 building_code = 3;</code>
     * @return The buildingCode.
     */
    int getBuildingCode();

    /**
     * <code>required .Employee.FloorNumber floor_number = 4;</code>
     * @return Whether the floorNumber field is set.
     */
    boolean hasFloorNumber();
    /**
     * <code>required .Employee.FloorNumber floor_number = 4;</code>
     * @return The floorNumber.
     */
    EmployeeOuterClass.Employee.FloorNumber getFloorNumber();

    /**
     * <code>required int64 salary = 5;</code>
     * @return Whether the salary field is set.
     */
    boolean hasSalary();
    /**
     * <code>required int64 salary = 5;</code>
     * @return The salary.
     */
    long getSalary();

    /**
     * <code>required string department = 6;</code>
     * @return Whether the department field is set.
     */
    boolean hasDepartment();
    /**
     * <code>required string department = 6;</code>
     * @return The department.
     */
    java.lang.String getDepartment();
    /**
     * <code>required string department = 6;</code>
     * @return The bytes for department.
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return Whether the cafeteriaCode field is set.
     */
    boolean hasCafeteriaCode();
    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return The cafeteriaCode.
     */
    java.lang.String getCafeteriaCode();
    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return The bytes for cafeteriaCode.
     */
    com.google.protobuf.ByteString
        getCafeteriaCodeBytes();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      floorNumber_ = 0;
      department_ = "";
      cafeteriaCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              employeeId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buildingCode_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              EmployeeOuterClass.Employee.FloorNumber value = EmployeeOuterClass.Employee.FloorNumber.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                floorNumber_ = rawValue;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              salary_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              department_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              cafeteriaCode_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeOuterClass.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeOuterClass.Employee.class, EmployeeOuterClass.Employee.Builder.class);
    }

    /**
     * Protobuf enum {@code Employee.FloorNumber}
     */
    public enum FloorNumber
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GROUND = 0;</code>
       */
      GROUND(0),
      /**
       * <code>FIRST = 1;</code>
       */
      FIRST(1),
      /**
       * <code>SECOND = 2;</code>
       */
      SECOND(2),
      ;

      /**
       * <code>GROUND = 0;</code>
       */
      public static final int GROUND_VALUE = 0;
      /**
       * <code>FIRST = 1;</code>
       */
      public static final int FIRST_VALUE = 1;
      /**
       * <code>SECOND = 2;</code>
       */
      public static final int SECOND_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FloorNumber valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static FloorNumber forNumber(int value) {
        switch (value) {
          case 0: return GROUND;
          case 1: return FIRST;
          case 2: return SECOND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FloorNumber>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FloorNumber> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FloorNumber>() {
              public FloorNumber findValueByNumber(int number) {
                return FloorNumber.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return EmployeeOuterClass.Employee.getDescriptor().getEnumTypes().get(0);
      }

      private static final FloorNumber[] VALUES = values();

      public static FloorNumber valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FloorNumber(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Employee.FloorNumber)
    }

    private int bitField0_;
    public static final int EMPLOYEE_ID_FIELD_NUMBER = 1;
    private long employeeId_;
    /**
     * <pre>
     *unique numbers that are used for serializing and deserializing data
     * </pre>
     *
     * <code>required int64 employee_id = 1;</code>
     * @return Whether the employeeId field is set.
     */
    @java.lang.Override
    public boolean hasEmployeeId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *unique numbers that are used for serializing and deserializing data
     * </pre>
     *
     * <code>required int64 employee_id = 1;</code>
     * @return The employeeId.
     */
    @java.lang.Override
    public long getEmployeeId() {
      return employeeId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_CODE_FIELD_NUMBER = 3;
    private int buildingCode_;
    /**
     * <code>required int32 building_code = 3;</code>
     * @return Whether the buildingCode field is set.
     */
    @java.lang.Override
    public boolean hasBuildingCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 building_code = 3;</code>
     * @return The buildingCode.
     */
    @java.lang.Override
    public int getBuildingCode() {
      return buildingCode_;
    }

    public static final int FLOOR_NUMBER_FIELD_NUMBER = 4;
    private int floorNumber_;
    /**
     * <code>required .Employee.FloorNumber floor_number = 4;</code>
     * @return Whether the floorNumber field is set.
     */
    @java.lang.Override public boolean hasFloorNumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .Employee.FloorNumber floor_number = 4;</code>
     * @return The floorNumber.
     */
    @java.lang.Override public EmployeeOuterClass.Employee.FloorNumber getFloorNumber() {
      @SuppressWarnings("deprecation")
      EmployeeOuterClass.Employee.FloorNumber result = EmployeeOuterClass.Employee.FloorNumber.valueOf(floorNumber_);
      return result == null ? EmployeeOuterClass.Employee.FloorNumber.GROUND : result;
    }

    public static final int SALARY_FIELD_NUMBER = 5;
    private long salary_;
    /**
     * <code>required int64 salary = 5;</code>
     * @return Whether the salary field is set.
     */
    @java.lang.Override
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int64 salary = 5;</code>
     * @return The salary.
     */
    @java.lang.Override
    public long getSalary() {
      return salary_;
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 6;
    private volatile java.lang.Object department_;
    /**
     * <code>required string department = 6;</code>
     * @return Whether the department field is set.
     */
    @java.lang.Override
    public boolean hasDepartment() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string department = 6;</code>
     * @return The department.
     */
    @java.lang.Override
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          department_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string department = 6;</code>
     * @return The bytes for department.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAFETERIA_CODE_FIELD_NUMBER = 7;
    private volatile java.lang.Object cafeteriaCode_;
    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return Whether the cafeteriaCode field is set.
     */
    @java.lang.Override
    public boolean hasCafeteriaCode() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return The cafeteriaCode.
     */
    @java.lang.Override
    public java.lang.String getCafeteriaCode() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cafeteriaCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cafeteria_code = 7;</code>
     * @return The bytes for cafeteriaCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCafeteriaCodeBytes() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cafeteriaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEmployeeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuildingCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFloorNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSalary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDepartment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, buildingCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, floorNumber_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(5, salary_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, department_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cafeteriaCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, employeeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, buildingCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, floorNumber_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, salary_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, department_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cafeteriaCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeOuterClass.Employee)) {
        return super.equals(obj);
      }
      EmployeeOuterClass.Employee other = (EmployeeOuterClass.Employee) obj;

      if (hasEmployeeId() != other.hasEmployeeId()) return false;
      if (hasEmployeeId()) {
        if (getEmployeeId()
            != other.getEmployeeId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasBuildingCode() != other.hasBuildingCode()) return false;
      if (hasBuildingCode()) {
        if (getBuildingCode()
            != other.getBuildingCode()) return false;
      }
      if (hasFloorNumber() != other.hasFloorNumber()) return false;
      if (hasFloorNumber()) {
        if (floorNumber_ != other.floorNumber_) return false;
      }
      if (hasSalary() != other.hasSalary()) return false;
      if (hasSalary()) {
        if (getSalary()
            != other.getSalary()) return false;
      }
      if (hasDepartment() != other.hasDepartment()) return false;
      if (hasDepartment()) {
        if (!getDepartment()
            .equals(other.getDepartment())) return false;
      }
      if (hasCafeteriaCode() != other.hasCafeteriaCode()) return false;
      if (hasCafeteriaCode()) {
        if (!getCafeteriaCode()
            .equals(other.getCafeteriaCode())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmployeeId()) {
        hash = (37 * hash) + EMPLOYEE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEmployeeId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasBuildingCode()) {
        hash = (37 * hash) + BUILDING_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingCode();
      }
      if (hasFloorNumber()) {
        hash = (37 * hash) + FLOOR_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + floorNumber_;
      }
      if (hasSalary()) {
        hash = (37 * hash) + SALARY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSalary());
      }
      if (hasDepartment()) {
        hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
        hash = (53 * hash) + getDepartment().hashCode();
      }
      if (hasCafeteriaCode()) {
        hash = (37 * hash) + CAFETERIA_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCafeteriaCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeOuterClass.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        EmployeeOuterClass.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeOuterClass.Employee.class, EmployeeOuterClass.Employee.Builder.class);
      }

      // Construct using EmployeeOuterClass.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        employeeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        buildingCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        floorNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        department_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cafeteriaCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee getDefaultInstanceForType() {
        return EmployeeOuterClass.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee build() {
        EmployeeOuterClass.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee buildPartial() {
        EmployeeOuterClass.Employee result = new EmployeeOuterClass.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.employeeId_ = employeeId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.buildingCode_ = buildingCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.floorNumber_ = floorNumber_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.salary_ = salary_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.department_ = department_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cafeteriaCode_ = cafeteriaCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeOuterClass.Employee) {
          return mergeFrom((EmployeeOuterClass.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeOuterClass.Employee other) {
        if (other == EmployeeOuterClass.Employee.getDefaultInstance()) return this;
        if (other.hasEmployeeId()) {
          setEmployeeId(other.getEmployeeId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasBuildingCode()) {
          setBuildingCode(other.getBuildingCode());
        }
        if (other.hasFloorNumber()) {
          setFloorNumber(other.getFloorNumber());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        if (other.hasDepartment()) {
          bitField0_ |= 0x00000020;
          department_ = other.department_;
          onChanged();
        }
        if (other.hasCafeteriaCode()) {
          bitField0_ |= 0x00000040;
          cafeteriaCode_ = other.cafeteriaCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEmployeeId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasBuildingCode()) {
          return false;
        }
        if (!hasFloorNumber()) {
          return false;
        }
        if (!hasSalary()) {
          return false;
        }
        if (!hasDepartment()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmployeeOuterClass.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmployeeOuterClass.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long employeeId_ ;
      /**
       * <pre>
       *unique numbers that are used for serializing and deserializing data
       * </pre>
       *
       * <code>required int64 employee_id = 1;</code>
       * @return Whether the employeeId field is set.
       */
      @java.lang.Override
      public boolean hasEmployeeId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *unique numbers that are used for serializing and deserializing data
       * </pre>
       *
       * <code>required int64 employee_id = 1;</code>
       * @return The employeeId.
       */
      @java.lang.Override
      public long getEmployeeId() {
        return employeeId_;
      }
      /**
       * <pre>
       *unique numbers that are used for serializing and deserializing data
       * </pre>
       *
       * <code>required int64 employee_id = 1;</code>
       * @param value The employeeId to set.
       * @return This builder for chaining.
       */
      public Builder setEmployeeId(long value) {
        bitField0_ |= 0x00000001;
        employeeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *unique numbers that are used for serializing and deserializing data
       * </pre>
       *
       * <code>required int64 employee_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmployeeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        employeeId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int buildingCode_ ;
      /**
       * <code>required int32 building_code = 3;</code>
       * @return Whether the buildingCode field is set.
       */
      @java.lang.Override
      public boolean hasBuildingCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 building_code = 3;</code>
       * @return The buildingCode.
       */
      @java.lang.Override
      public int getBuildingCode() {
        return buildingCode_;
      }
      /**
       * <code>required int32 building_code = 3;</code>
       * @param value The buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCode(int value) {
        bitField0_ |= 0x00000004;
        buildingCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 building_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buildingCode_ = 0;
        onChanged();
        return this;
      }

      private int floorNumber_ = 0;
      /**
       * <code>required .Employee.FloorNumber floor_number = 4;</code>
       * @return Whether the floorNumber field is set.
       */
      @java.lang.Override public boolean hasFloorNumber() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .Employee.FloorNumber floor_number = 4;</code>
       * @return The floorNumber.
       */
      @java.lang.Override
      public EmployeeOuterClass.Employee.FloorNumber getFloorNumber() {
        @SuppressWarnings("deprecation")
        EmployeeOuterClass.Employee.FloorNumber result = EmployeeOuterClass.Employee.FloorNumber.valueOf(floorNumber_);
        return result == null ? EmployeeOuterClass.Employee.FloorNumber.GROUND : result;
      }
      /**
       * <code>required .Employee.FloorNumber floor_number = 4;</code>
       * @param value The floorNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFloorNumber(EmployeeOuterClass.Employee.FloorNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        floorNumber_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Employee.FloorNumber floor_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloorNumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        floorNumber_ = 0;
        onChanged();
        return this;
      }

      private long salary_ ;
      /**
       * <code>required int64 salary = 5;</code>
       * @return Whether the salary field is set.
       */
      @java.lang.Override
      public boolean hasSalary() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int64 salary = 5;</code>
       * @return The salary.
       */
      @java.lang.Override
      public long getSalary() {
        return salary_;
      }
      /**
       * <code>required int64 salary = 5;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(long value) {
        bitField0_ |= 0x00000010;
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 salary = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000010);
        salary_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object department_ = "";
      /**
       * <code>required string department = 6;</code>
       * @return Whether the department field is set.
       */
      public boolean hasDepartment() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string department = 6;</code>
       * @return The department.
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            department_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string department = 6;</code>
       * @return The bytes for department.
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string department = 6;</code>
       * @param value The department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        department_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string department = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartment() {
        bitField0_ = (bitField0_ & ~0x00000020);
        department_ = getDefaultInstance().getDepartment();
        onChanged();
        return this;
      }
      /**
       * <code>required string department = 6;</code>
       * @param value The bytes for department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        department_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cafeteriaCode_ = "";
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @return Whether the cafeteriaCode field is set.
       */
      public boolean hasCafeteriaCode() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @return The cafeteriaCode.
       */
      public java.lang.String getCafeteriaCode() {
        java.lang.Object ref = cafeteriaCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cafeteriaCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @return The bytes for cafeteriaCode.
       */
      public com.google.protobuf.ByteString
          getCafeteriaCodeBytes() {
        java.lang.Object ref = cafeteriaCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cafeteriaCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @param value The cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCafeteriaCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cafeteriaCode_ = getDefaultInstance().getCafeteriaCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cafeteria_code = 7;</code>
       * @param value The bytes for cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final EmployeeOuterClass.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeOuterClass.Employee();
    }

    public static EmployeeOuterClass.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeOuterClass.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\"\337\001\n\010Employee\022\023\n\013employe" +
      "e_id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\025\n\rbuilding_cod" +
      "e\030\003 \002(\005\022+\n\014floor_number\030\004 \002(\0162\025.Employee" +
      ".FloorNumber\022\016\n\006salary\030\005 \002(\003\022\022\n\ndepartme" +
      "nt\030\006 \002(\t\022\026\n\016cafeteria_code\030\007 \001(\t\"0\n\013Floo" +
      "rNumber\022\n\n\006GROUND\020\000\022\t\n\005FIRST\020\001\022\n\n\006SECOND" +
      "\020\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "EmployeeId", "Name", "BuildingCode", "FloorNumber", "Salary", "Department", "CafeteriaCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
